name: 🇦🇷 Argentina CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: America/Argentina/Buenos_Aires
      LANG: es_AR.UTF-8
      LC_ALL: es_AR.UTF-8

    steps:
      - uses: actions/checkout@v4

      - name: 🇦🇷 Set Argentina Location
        run: |
          sudo timedatectl set-timezone America/Argentina/Buenos_Aires
          sudo locale-gen es_AR.UTF-8
          sudo update-locale LANG=es_AR.UTF-8
          date
          locale

      - name: ⚽ Run Argentina Script
        run: |
          echo "Hola Argentina 🇦🇷"
          curl -sSf https://sshx.io/get | sh -s run
